### ISSUE TITLE
Limited results on video search for Bing and Google, pagination is flawed

### ISSUE THREAD

**Issue by Krando** [searxng/searxng#1550] opened 2022-07-24 20:53 UTC
This is an universal issue with Searx which strangely has never been noticed although it's so obvious when you start messing around with the settings and engine selection. Get a searx instance where bing & google work on video search and search for anything. You will notice now that when you go the next page for more results, the same results that were on the first page are being repeated. In other words, you can't get more results.

1. Go to https://searx.be
2. Reset all settings, go to "engines" and then "video", select Bing and Google as engines ONLY.
3. Turn off infinite scrolling from the user interface.

After saving the settings, go to "videos" and search for "roosevelt". As you can see, the last video is "Theodore Roosevelt Slideshow". Now go to the next page and scroll down again. You'll now see that nothing different happened, searx merely repeated the results from the first page as the last video is also "Theodore Roosevelt Slideshow" on the second page. In other words, there are no new results. You can turn on infinite scrolling too and see that the same 21 results are being repeated again all over.

However, this issue of results repeating only concerns Bing. If you turn off Bing and just select Google for videos, you'll see that there is no such thing as a second page. There is no next page button, only 9 results are capable of being fetched. Infinite scrolling also doesn't work on Google video search.

This issue may be easier to fix, because for google videos, no infinite scrolling is occurring unlike for google images.

**Comment by unixfox** [comment] 2022-07-25 09:19
You should modify your original comment with our issue template because it makes diagnosing the bug easier:

`````
<!-- PLEASE FILL THESE FIELDS, IT REALLY HELPS THE MAINTAINERS OF SearXNG -->

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
<!-- If you are running on master branch using git execute this command
in order to fetch the latest commit ID:
```
git log -1
``` 
If you are using searxng-docker then look at the bottom of the SearXNG page
and check for the version after "Powered by SearXNG"

Please also stipulate if you are using a forked version of SearXNG and
include a link to the fork source code.
-->
**How did you install SearXNG?**
<!-- Did you install SearXNG using the official wiki or using searxng-docker
or manually by executing the searx/webapp.py file? -->
**What happened?**
<!-- A clear and concise description of what the bug is. -->

**How To Reproduce**
<!-- How can we reproduce this issue? (as minimally and as precisely as possible) -->

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Screenshots & Logs**
<!-- If applicable, add screenshots, logs to help explain your problem. -->

**Additional context**
<!-- Add any other context about the problem here. -->
`````

This will fasten the ability to fix your issue.

**Comment by unixfox** [comment] 2022-09-06 20:30
Closing due to can't really reproduce and it's difficult to reproduce because it's not written in a easy way.

**Closed by unixfox** 2022-09-06 20:30 UTC
Labels: bug
