### ISSUE TITLE
Bug: dictzone engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1536] opened 2022-07-22 08:30 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.19-a983db02

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-07-22 17:02
I can't reproduce a HTTP 403 (nor any other issue) / I tested `!dc en-de shopping basket`

I close the issue / if you have some more hints to reproduce the issue, we can reopen.

**Closed by return42** 2022-07-22 17:02 UTC
Labels: invalid:duplicate, bug
