### ISSUE TITLE
Can't switch language while Autodetect search language is activated

### ISSUE THREAD

**Issue by Tiritibambix** [searxng/searxng#2123] opened 2023-01-22 12:05 UTC
**Version of SearXNG**
Searxng-docker  2023.01.21+674dae94 searxng/searxng:latest

**How did you install SearXNG?**
```
version: '3.7'
services:
  redis:
    container_name: searxng-redis
    image: "redis:alpine"
    restart: unless-stopped
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
     - "8082:8080"
    volumes:
      - ./Searxng/:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://my.domain.tld/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default
```

**What happened?**
Sometimes, Autodetect search language is wrong.
I then select (by scrolling, while hiting a key wold be easier) desired language, which launches the search again, but it returns back to bad language.

**How To Reproduce**
- Search for "vaseline lip therapy"
- It autodetects Polski
- Switch to French
- It switches back to Polski

**Expected behavior**
It should relaunch the search with selected language
Language should be selectable by hitting a key (eg F for French) to avoid scrolling

**Comment by dalf** [comment] 2023-01-22 13:30
https://github.com/searxng/searxng/pull/2027 should fix your issue: in the PR, `auto` becomes a language, so you can easily pick another language.

**Comment by return42** [comment] 2023-01-22 13:32
At its current state you have to disable autodetection of languages to select an language by your own

[To SearXNG maintainers; please take into account: under some circumstances the auto-detection of the language of this plugin could be detrimental to users expectations. Its not recommended to activate this plugin by default. It should always be the user’s decision whether to activate this plugin or not.](https://docs.searxng.org/src/searx.plugins.autodetect_search_language.html)

I close this issue, its a duplicate of https://github.com/searxng/searxng/issues/2018

**Closed by return42** 2023-01-22 13:32 UTC
Labels: bug

**Comment by Tiritibambix** [comment] 2023-01-29 13:17
I'm sorry I don't understand.

You're mentioning #2018 and #2027 . I'm running the latest version and I see no change.

**Comment by return42** [comment] 2023-01-29 13:33
both are "open"
