### ISSUE TITLE
Duplicated Date header in response

### ISSUE THREAD

**Issue by ononoki1** [searxng/searxng#1363] opened 2022-06-24 11:26 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.06.22-ed1ff4b8

**How did you install SearXNG?**
Manually executing the searx/webapp.py file.

**What happened?**
Response header has duplicated `Date` header when accessing `/favicon.ico`.

**How To Reproduce**
Run `curl -I http://127.0.0.1:8888/favicon.ico` in an machine with SearXNG installed and listened on port 8888.

**Expected behavior**
No duplicated header.

**Screenshots & Logs**
Output of `curl -I http://127.0.0.1:8888/favicon.ico`:
```txt
HTTP/1.1 200 OK
Server: Werkzeug/2.1.2 Python/3.10.5
Date: Fri, 24 Jun 2022 11:12:11 GMT
Content-Disposition: inline; filename=favicon.png
Content-Type: image/vnd.microsoft.icon
Content-Length: 5096
Last-Modified: Thu, 19 May 2022 04:56:21 GMT
Cache-Control: no-cache
Date: Fri, 24 Jun 2022 11:12:11 GMT
Server-Timing: total;dur=0.847, render;dur=0
Connection: close
```

Other requests (like `/` or `/search?q=test`) are not affected. Here is output of `curl -I http://127.0.0.1:8888/search?q=test`:
```txt
HTTP/1.1 200 OK
Server: Werkzeug/2.1.2 Python/3.10.5
Date: Fri, 24 Jun 2022 11:19:56 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 37028
Server-Timing: total;dur=572.75, render;dur=7.108, total_0_wikipedia;dur=82.76, total_1_google;dur=563.3, load_0_wikipedia;dur=82.398, load_1_google;dur=548.227
Connection: close
```

**Additional context**
Thanks for NGINX latest release, adding support for logging duplicated upstream header into error log, which made me find this issue. The NGINX log is like this:
```txt
2022/06/24 18:57:05 [warn] xxx#xxx: *2941 upstream sent duplicate header line: "Date: Fri, 24 Jun 2022 10:57:05 GMT", previous value: "Date: Fri, 24 Jun 2022 10:57:05 GMT", ignored while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: search.ononoki.org, request: "GET /favicon.ico HTTP/3.0", upstream: "http://127.0.0.1:8888/favicon.ico", host: "search.ononoki.org"
```

**Comment by return42** [comment] 2023-04-10 08:48
@ononoki1 sorry for the late response on the issue you reported: I tackle with this issue .. the issue occur only when the debugger is activated:

https://github.com/searxng/searxng/blob/3372fcdb491d59d3ca2e11d040ff7ef34dfa675a/searx/webapp.py#L1397-L1399

and a [`flask.send_from_directory(..)](https://flask.palletsprojects.com/en/2.2.x/api/#flask.send_from_directory) is called ..

https://github.com/searxng/searxng/blob/3372fcdb491d59d3ca2e11d040ff7ef34dfa675a/searx/webapp.py#L1299-L1301
 
----

The issue comes from the "werkzeug" library that is used by Flask .. the issue is known:

- https://github.com/pallets/werkzeug/issues/2500

> Don't use the development server in production. This isn't actually an error, and the fix would add a lot of complexity to the server handler.

.. sorry, there is nothing we can do / I'm going to close this issue.

**Closed by return42** 2023-04-10 08:48 UTC
Labels: bug
