### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by nityanand-thakur** [searxng/searxng#1523] opened 2022-07-18 02:48 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.14-e67ed894

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 75
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 25
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/startpage.py:66`
  * Function: `raise_captcha`
  * Code: `raise SearxEngineCaptchaException(suspended_time=7 * 24 * 3600)`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('413', 'Request Entity Too Large', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-07-22 17:06
Duplicate of https://github.com/searxng/searxng/issues/1081

**Closed as completed by return42** 2022-07-22 17:06 UTC
Labels: invalid:duplicate
