### ISSUE TITLE
Error in translation license

### ISSUE THREAD

**Issue by comradekingu** [searxng/searxng#231] opened 2021-07-28 18:18 UTC
https://weblate.bubu1.eu/projects/searxng/searxng/#information says "GPLv3-only", whereas
many files in the source code repo are "or any later version"
https://github.com/searxng/searxng/blob/6c0114567e7ba1b3f4a54327eddf658b7474ca58/searx/version.py#L6

Ostensibly that means (?) current translations are also GPLv3+.
In any event, going or-later for everything causes fewer problems in that it is compatible, and has the most flexibility down the road.

**Comment by dalf** [comment] 2021-07-29 07:55
Updated.

**Comment by return42** [comment] 2021-07-30 15:32
I close this issue / ask for reopen this issue if you think the issue is not solved serious.

**Closed by return42** 2021-07-30 15:32 UTC
Labels: bug

**Comment by comradekingu** [comment] 2021-07-30 16:39
AGPLv3+ makes a lot more sense with the network protections. Good choice :)

**Comment by return42** [comment] 2021-07-30 16:46
FYI: https://github.com/searxng/searxng/blob/master/LICENSE
