### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by Linerly** [searxng/searxng#1097] opened 2022-04-15 13:42 UTC
**Is your feature request related to a problem? Please describe.**
I would like to have SearXNG to be an 'app' (progressive web app), so that I can open SearXNG directly from my home screen on my phone

**Describe the solution you'd like**
Add PWA support in SearXNG (see https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen)

**Additional context**
DuckDuckGo for example has this feature

**Comment by mrpaulblack** [comment] 2022-04-16 06:55
Duplicate of https://github.com/searxng/searxng/issues/563

**Closed as completed** 2022-04-16 06:57 UTC
