### ISSUE TITLE
Bug: google engine access denied

### ISSUE THREAD

**Issue by vgivanovic** [searxng/searxng#1904] opened 2022-10-29 00:14 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.24

**How did you install SearXNG?**
Added via "Find more search engines" in Firefox Settings:Search

**What happened?**
No results when search string is submitted to SearCNG search engine. See error message below.

**How To Reproduce**
Search for something.

**Expected behavior**
Search results

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

![Screenshot_2022-10-28_17-13-28](https://user-images.githubusercontent.com/169579/198752791-fd323437-664e-4794-b8b9-b65dce6df219.png)

**Comment by return42** [comment] 2022-10-29 07:07
@unixfox I assume it was an temporary issue on searx.be / otherwise please reopen, I am gonna close this entry

**Comment by unixfox** [comment] 2022-10-29 07:12
Reopening because this bug has to be solved.
@tiekoetter can reproduce the issue too

**Comment by vgivanovic** [comment] 2022-10-29 16:43
No longer occurs for me. I'm OK with closing this bug.

**Comment by random3456345** [comment] 2022-10-30 18:19
It is happening to me too when I use a particular public instance, even though the page /stats?engine=google says the reliability is 100%

**Comment by random3456345** [comment] 2022-10-31 20:18
It works now.

**Comment by vojkovic** [comment] 2022-11-04 13:32
Same thing is happening to me on my instance and It's also showing me a 100% reliability.

EDIT: Began working again a day later.

**Comment by Shituation** [comment] 2022-11-04 17:33
Take my friendly advice. Move on to other search engines. These people censores you.

**Comment by k-l-o-n-d-i-k-e** [comment] 2022-11-06 13:30
It's also happening on northboot instance. Has been like that for a couple of days now.

![image](https://user-images.githubusercontent.com/108140943/200173490-4b1a1ff3-c078-4c25-b00b-09a9990f7a0b.png)

**Closed** 2022-11-11 09:46 UTC
Labels: bug
