### ISSUE TITLE
Bug: tineye engine

### ISSUE THREAD

**Issue by maldonadoeli** [searxng/searxng#1469] opened 2022-07-06 20:34 UTC
Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('422', 'Unprocessable Entity', 'tineye.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`
https://search.networkchuck.coffee/

**Comment by return42** [comment] 2022-07-06 21:17
Duplicate of https://github.com/searxng/searxng/issues/1449 and solved in https://github.com/searxng/searxng/pull/1456

**Closed by return42** 2022-07-06 21:17 UTC
Labels: bug
