### ISSUE TITLE
Bug: gigablast engine

### ISSUE THREAD

**Issue by aming-r** [searxng/searxng#2063] opened 2022-12-30 12:18 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.16-b9274821

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by return42** [comment] 2022-12-30 12:46
Sorry, but missing all informations in your form .. How can we help without providing the required information? .. going to close this issue.

May your issue is a duplicate of https://github.com/searxng/searxng/issues/1454

**Closed as completed by return42** 2022-12-30 12:46 UTC
Labels: invalid:duplicate
