### ISSUE TITLE
Bug: reddit engine

### ISSUE THREAD

**Issue by rodgui** [searxng/searxng#3633] opened 2024-07-02 17:01 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.6.30+39aaac40d

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by Bnyro** [comment] 2024-07-02 18:43
Duplicate of https://github.com/searxng/searxng/issues/3444

**Closed by Bnyro** 2024-07-02 18:43 UTC
Labels: invalid:duplicate, bug
