### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by Buhtig1234567890** [searxng/searxng#1960] opened 2022-11-17 02:50 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.07

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by Buhtig1234567890** [comment] 2022-11-17 02:51
We want this to be in working condition

**Comment by jasonbrown1965** [comment] 2022-11-17 04:54
Similar result to above - other instances seem to be okay - targeted complaint attack ?
![image](https://user-images.githubusercontent.com/11400799/202359419-cc4fe2ac-e729-4f28-83cb-7bece2028771.png)

Here via :
https://searx.be/stats?engine=google

Sorry this does not adhere to issue reporting guidelines, on concussion leave

**Comment by return42** [comment] 2022-11-17 05:58
> Version: 2022.11.07

update your instance .. duplicate of https://github.com/searxng/searxng/issues/1935 and solved in PR https://github.com/searxng/searxng/pull/1950

@unixfox if I'm not wrong, searx.be needs an update .. right?

**Closed by return42** 2022-11-17 05:58 UTC
Labels: invalid:duplicate, bug

**Comment by unixfox** [comment] 2022-11-17 07:23
> > Version: 2022.11.07
> 
> update your instance .. duplicate of #1935 and solved in PR #1950
> 
> @unixfox if I'm not wrong, searx.be needs an update .. right?

yes I haven't had the time due to https://github.com/searxng/searxng/issues/1951

**Comment by unixfox** [comment] 2022-11-23 10:26
Instance now up to date.
