### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1883] opened 2022-10-25 05:03 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.20-7f2185ce

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.DecodingError
  * Percentage: 95
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 5
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-10-26 05:51
See https://github.com/searxng/searxng/issues/1815#issuecomment-1282220775

duplicate of https://github.com/searxng/searxng/search?q=httpx.DecodingError&type=issues

**Closed as completed** 2022-10-26 05:51 UTC
Labels: invalid:duplicate
