### ISSUE TITLE
Please make the host and port settings for the MySQL engine configurable.

### ISSUE THREAD

**Issue by virtadpt** [searxng/searxng#3165] opened 2024-01-29 01:07 UTC
**Is your feature request related to a problem? Please describe.**
The searxng/searx/engines/mysql_server.py search adapter is hardcoded to only connect to 127.0.0.1, port 3306/tcp.  This makes it not possible to connect to the database server my hosting provider is running for me (which is on a different host), or connect to the MySQL-alike server running on my server (on a port that isn't 3306).

**Describe the solution you'd like**
Please add 'auth_plugin', 'hostname', and 'port' fields to the searxng/searx/settings.yml file for the MySQL engine.  Please modify searxng/searx/engines/mysql_server.py to reference those fields in .../settings.yml to properly configure the engine.  Additionally, because I know this'll impact a few folks, make sure that having a blank username and/or password (or missing 'username' and `password` fields) doesn't cause a crash (because there are a few things out there that emulate the MySQL wire protocol but by default don't require credentials to log in (e.g., Manticore)).

**Describe alternatives you've considered**
Right now I'm sorta-kinda faking it with cURL and jq in a shell script but it's far from optimal.

**Comment by unixfox** [comment] 2024-01-29 07:07
Do you want to contribute to this new change? Doesn't sounds like a difficult task.

**Comment by return42** [comment] 2024-01-29 15:15
> The searxng/searx/engines/mysql_server.py search adapter is hardcoded to only connect to 127.0.0.1, port 3306/tcp.

You refer to this section from the source code (?) ..

https://github.com/searxng/searxng/blob/559b8606189ff44eee6e8bcde2763daf3c2cbd7c/searx/engines/mysql_server.py#L37-L42

You can overwrite these settings by adding them to the config of your MySQL engine ..

https://github.com/searxng/searxng/blob/559b8606189ff44eee6e8bcde2763daf3c2cbd7c/searx/settings.yml#L1886-L1894

**Comment by virtadpt** [comment] 2024-01-29 18:00
> Do you want to contribute to this new change? Doesn't sounds like a difficult task.

I'm still trying to get it past legal at $dayjob.  It's not a project I initiated so I have a bunch of hoops to jump through.

**Comment by virtadpt** [comment] 2024-01-29 18:01
@return42 They are actually used?  Nice.  I'll give it a try tonight.

**Comment by virtadpt** [comment] 2024-01-31 01:56
Negative:

```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)
2024-01-30 17:54:40,251 WARNING:searx.engines.mysql: ErrorContext('searx/engines/mysql_server.py', 73, 'with _connection.cursor() as cur:', 'mysql.connector.errors.OperationalError', None, ()) False
2024-01-30 17:54:40,252 ERROR:searx.engines.mysql: engine mysql : exception : MySQL Connection not available.
```

The database server in question does not have SSL enabled because it is hardwired for localhost:9306.

**Comment by virtadpt** [comment] 2024-01-31 02:49
Let's try this again.

Not working.  I'm digging into it right now by going through the code in searxng/searx/engines/mysql_server.py and running through the query process.  I get the same error that I do when I have SearxNG run the query:

```
import mysql.connector
connection = mysql.connector.connect(user="", password="", host="127.0.0.1",
    port=9306, database="Manticore")
query_params = {"query": "lisp compiler"}

# If I execute this query from the MySQL shell, it works.
query = "SELECT id, title, url FROM articles WHERE match('lisp compiler');"

with connection.cursor() as cursor:
    cursor.execute(query, query_params)

    # The same thing happens with
    # cursor.execute(query)
```

Even a basic form of the query above errors out:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/drwho/searxng/env/lib/python3.8/site-packages/mysql/connector/conn
ection_cext.py", line 728, in cursor
    raise OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.
```

Nothing in the database server logs, I'm tailing them in realtime.

**Comment by return42** [comment] 2024-01-31 06:52
Sorry, I do not have MySQL at hand to test .. but when you start `mysql` on the command line it uses some defaults to connect to the database / find out theses defaults [1] and retry your little example with this defaults [2].

[1] https://stackoverflow.com/a/2485758
[2] https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysql-connector-connect.html

**Comment by virtadpt** [comment] 2024-01-31 18:25
I dumped my defaults (can post them if you like) and compared them to my research code.  They appear to line up as expected; stuff that has no default is specifically given in the evocation of `mysql.connector.connect()`, the one default that is different (the connection port) gets explicitly set.  That is functionally the same as

```
drwho@server:~ () $ mysql --host 127.0.0.1 --port 9306
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 5.0.2 348514c86@220530 dev git branch HEAD (no branch)

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    18
Current database: *** NONE ***
+-----------+
| Databases |
+-----------+
| Manticore |
+-----------+
1 row in set (0.00 sec)

mysql> use Manticore;
No connection. Trying to reconnect...
Connection id:    19
Current database: *** NONE ***

Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    20
Current database: Manticore

+----------+-------+
| Index    | Type  |
+----------+-------+
| articles | local |
+----------+-------+
```

Queries work as expected, also:

```
mysql> SELECT COUNT(*) FROM articles WHERE MATCH('lisp compiler');
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    24
Current database: Manticore

+----------+
| count(*) |
+----------+
|       17 |
+----------+
1 row in set (0.00 sec)
```

**Comment by return42** [comment] 2024-01-31 19:16
May this error ..

> `ERROR 2013 (HY000): Lost connection to MySQL server during query`

is cause of the trouble ..

> `mysql.connector.errors.OperationalError: MySQL Connection not available.`

I'm not a MySQL expert .. but in the articles I found they had an issue with the DB `connect_timeout` .. can you check?  What happens if you increase the timeout e.g. by:

```
SET GLOBAL connect_timeout = 6000;
```

Further see https://dba.stackexchange.com/a/162471

**Comment by return42** [comment] 2024-02-03 19:02
@virtadpt I close this issue since your initial request *"make the host and port settings for the MySQL engine configurable."* is already possible.

If you have any remarks you can continue to post comments here / even the issue is closed, we will see you comments.

**Closed as completed by return42** 2024-02-03 19:02 UTC

**Comment by virtadpt** [comment] 2024-02-04 00:23
@return42 Nope, that's sorted.  Thank you very much.  It might be a good idea to have those config options in the searxng/searx/settings.yml file by default but that's just a QoL kind of thing.

Incidentally, I think it's a functional incompatibility in the python-mysql-connector Python module.  I've been tinkering with it off and on all week, and I can't get it to work.  I'm working around it in the same way I did before (https://github.com/virtadpt/exocortex-halo/tree/master/scripts/manticore-and-searxng), just updated a bit for SearxNG.
