### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by YaaniuNotFound** [searxng/searxng#1799] opened 2022-09-23 12:04 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.08.01-7c9c1124

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.DecodingError
  * Percentage: 100
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-09-26 06:20
Next time please fill out the form and do not open a issue for already reported and fixed problem.

Duplicate of

* https://github.com/searxng/searxng/issues/1786
* https://github.com/searxng/searxng/issues/1785
* https://github.com/searxng/searxng/issues/1779
* https://github.com/searxng/searxng/issues/1778

Fixed in:

- https://github.com/searxng/searxng/pull/1787

**Closed by return42** 2022-09-26 06:20 UTC
Labels: brave-engine, bug
