### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by Kazak-ops** [searxng/searxng#1735] opened 2022-09-01 10:24 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.08.31-8a56e3d4

**How did you install SearXNG?**
I installed using the docker container posted on unraid community application s
**What happened?**
Error! Engines cannot retrieve results:

google ( [Suspended: too many requests](https://search.plutonic-gaming.com/stats?engine=google) )

**How To Reproduce**
Install as standard on docker container and then run a search, seems to keep happening

**Expected behavior**
To load google results, all other results load

**Screenshots & Logs**
<img width="1160" alt="Screen Shot 2022-09-01 at 11 24 08" src="https://user-images.githubusercontent.com/56021888/187892356-0aab5a42-179e-430d-af99-706d86a3bc2e.png">

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-09-01 10:45
did you tried `use_mobile_ui` ... https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

```yaml
- name: google
  ...
  use_mobile_ui: true
```

Duplicate of https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+use_mobile_ui

**Closed as completed by return42** 2022-09-01 10:45 UTC
Labels: invalid:duplicate

**Comment by atuleu** [comment] 2022-10-26 07:56
@return42 Should not then just be enabled by default ?
