### ISSUE TITLE
Bug: google scholar engine

### ISSUE THREAD

**Issue by nimna29** [searxng/searxng#1769] opened 2022-09-14 20:22 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.09.01-174e5242

**How did you install SearXNG?**
using searxng-docker

**What happened?**
I added google scholar as a one of search engines, but it is not working. Error Message: "Suspended: access denied"

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/77341013/190254596-fc59c7f0-7ce6-47ac-a69a-1be29cddaa2e.png)

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2023-01-08 11:04
For reference / I addressed this issue in my rework of locales & languages: [`[mod] Google: reversed engineered & upgrade to data_type: traits_v1 `](https://github.com/return42/searxng/commits/master)

**Comment by return42** [comment] 2023-01-08 12:14
The issue is not solved in SearXNG's master branch .. I reopen this issue.

**Comment by return42** [comment] 2023-03-29 08:03
Issue is fixed by:

- https://github.com/searxng/searxng/pull/2269

**Closed by return42** 2023-03-29 08:03 UTC
Labels: bug
