### ISSUE TITLE
Can't copy text directly from results

### ISSUE THREAD

**Issue by ValiumBear** [searxng/searxng#1260] opened 2022-05-31 16:37 UTC
If you try marking any text from results (except the header of the result) it will instantly stop marking once you release the mouse button.
I consider it essential to be able to copy text from results. Hope you can fix this.

Version: 2022.05.29-38403ee5

**Comment by mrpaulblack** [comment] 2022-05-31 21:37
This is a duplicate of https://github.com/searxng/searxng/issues/794; Closing.

**Closed by mrpaulblack** 2022-05-31 21:37 UTC
Labels: bug
