### ISSUE TITLE
Settings-URL dont work / gets ignored, Settings always default from the instance.

### ISSUE THREAD

**Issue by solisinvictum** [searxng/searxng#1365] opened 2022-06-24 19:54 UTC
Hello Guys,

yesterday i found out that searxng have implemented a center view (https://github.com/searxng/searxng/issues/1175#issuecomment-1164997639).

And started using it. But know i found out, that this dont work right.

After some experiments, i found out this is because  the Setting-URL dont work / gets ignored.

Than i thought it is a problem with the instance i choosed (https://searx.tiekoetter.com). 

But sadly this occurs on every instance listed here: https://searx.space/ (i tested all DE ones). 

Saving the Setting with a Cookie works, but on my system the cookie gets isolated in each tab, and removed after i left the site or close it. 

Here is a example: 

https://searx.tiekoetter.com/search?preferences=eJxtV81y2zgMfpr4omlm2-7Obg8-td19gd41EAlJiEhC5Y9t5ekXtKSIjHOIY4IgAH74AMIKIg7sCcN5QIcezMmAGxIMeNb46cfPk2EFJi9OkCIrtrPBiOeBeTB4Iiua7ez5tpx_-YQni3Fkff7v569TgB4Dglfj-Y9THNHiOVA-fvIYkomhZdc6vLYRuvO_YAKeNFMrm2wu6M8MsnxmP5zWY22Ii0SSwzgpdBF9C4YGK19X36Av4BTqdvO62vyd0C8tuTZSlON3TXI9OYpiUnk2ZhVqCtAZOY5uICeIaMRXcdLaFEg9ffnekRvadsNJ1jqpKf8N_LG0uaMT2nb9L3u_r-BiqRwi-DhnDAvhAiPzg6ARqMRW_swiTjF1cuxCGrmS7OFqILNYjiQwH2oXssjFuvNwqbx71JokyMCKwDQWNYGIrzSRhghV9PjqwJYSJ8Z8hYYeGo13tCWOUG7dwWjWQMqABOX6rnfJg17vyU0EqoD3St1SesAo93dGkllJPV9Jl5J8t455qsLrDanJV9anfAfwy_uzgZNXlY-ZvFRWB6Lak7kfH2bWOoPzDtg3-YNiATQb0pG9F66HQ1PjhQRDoVAdJkkSAsWHOC-8vKOaThqFHSzl6XPYy0xiKspX8De6SLCKUGpKBMmF2UAYC1cDxTF124EOnFZg54OAa494zJy4pxQOvXnkmDlqYZYVz-hy_Fg4mhH9O7qHNKNPIeO0xhum1CUX07Ye7873zVezeFJVfrMfIGG7kDpghvW46743p05YABt1j33NakLfHJcXszHX7H2RobbC-NKbQGVg17Z0U4aTPiCwIFx-u4shqUq_NNw3it0gHbFsIgFngrXFFXi8ftpOHfT4_PXr37djeWXTe7Bg5hHKy2xpkuQuDcxzwS-fbGcq0FECjaSaoEY24Esza0SKNTb5o8CiKubI0yLpDiNP4A5XgrQURGlv1jnfx1op9SleimDcbDcn0sRD8NiX6m4BOMzniDr0ww4wdyHisw_bOudbss3V3btlQLtrlCBZvhDWrQixCdzHK3hstBBHSbEu29Fee8795siD146mqr6fvv_19M8Xvoq8eXn6_ufTt2-vywTNzCYIMeoXZgY1wUAh7nTKnUQqeJKwrlfsishGEE7kjzeeojQxi_u1VkIIcfZ8dRQ7ebwwvrUBNUo7aaiqnSvfaGL3LLkOi2O32KqrWH4RP6Vkkl4KoYCXHBRhwjw1lrznog1-vhWc16TiK9d9fK-SLAlU2LYSjhX8m-jBBSONWB8tLhPyd-JYmSKru0NFcpdLi10u-7wWBi-V_gsJf48Da6PfVzIu3aQXeqreyhljHkfWqv1QXD965cbDHLHgXBlJnaTisldD8oaOcE_SyqqxJiMwZ8qUJuSQPC6qejI2zj94H7bW-qBZXWCTfdApcrWFKDUTpePvbX-dBioL8qzKk1I3yjDLQNMvh4CcsIg4lfVYyHa11fzDVe6jxYP0DrqMDenWZLA2XGVWUxPL09Qbvu7lEjUNw0E9GG3GdaXOMVHOJgn24ZzzeXveVs8M7TrwXr3MolsLPbZlUmvlZZxwCW85_NjQmJ_ldfFgZeQQZUhDcSPNSz26MfJWxTtxa_nGVXmY1fojYZG52khn-0DT9DJg9_ywIwWYH8pWGCn-bQbvJA-ApP_8P7I8tls=

**Comment by tiekoetter** [comment] 2022-06-25 07:26
@solisinvictum 
The "URL to restore your preferences in another browser" works for me as intended; It saves the settings as cookies. If your system deletes cookies you should consider changing that behavior.

The "Search URL of the currently saved preferences" also works as intended for me as you add this to your search engine config in your browser. Nothing is saved here as a cookie.

**Comment by solisinvictum** [comment] 2022-06-25 12:57
> The "Search URL of the currently saved preferences" also works as intended for me as you add this to your search engine config in your browser. Nothing is saved here as a cookie.

I have it set as search engine in my browser (ungoogled-chromium). Sadly, dont work. I tested standard Firefox installation too. Dont work either. 

> The "URL to restore your preferences in another browser" works for me as intended; It saves the settings as cookies. If your system deletes cookies you should consider changing that behavior.

This works kind of. With this method it isnt possible to add &q=search_something. So this url cant be used to search over the url bar from the browser. 

There is no way to change how cookies are handled. Because of tracking etc i dont want them have saved.

**Comment by solisinvictum** [comment] 2022-06-25 16:24
Ok i found a workaround for me.

i configured searxng like i wanted, copied both urls (cookie and the url one), and use them both parallel. the cookie/transfer one, i set as startpage wich gets opened everytime browser starts, and the url one gets used if i search from the addressbar.

**Comment by dalf** [comment] 2022-06-25 17:20
I'm not sure to understand the issue, just in case, it might be not useful for you:
* `https://searx.tiekoetter.com/preferences?save=1&preferences=....` saves your preferences into a cookie and returns to the front page.
* So this link can be use at the start page of your browser.

**Comment by return42** [comment] 2022-07-09 07:23
@solisinvictum looks like your issue is solved .. I'm going to close this issue. If not solved give some more information about what you expect and we can reopen.

**Comment by solisinvictum** [comment] 2022-07-11 10:52
No, sadly this issue isnt solved.

The first URL under the "Cookie" Section still dont work. Only in combination with the secound one.

First the Site must be loaded with the secound url, than the first one works.

So i need to load the Site atleast 2 times first, before i can start using it.

And today again, i must the third time set all settings again, and change both urls in my browser to the new urls.

Because the old urls one stopped working (wich worked ~6 days). 

This seems to happen after every update of the instance, because now the instance is at 2022.07.10-b6d59dec and the urls i generated prior this version dont work again.

(EDIT: Just for interest: Why isnt the Settings handled like at duckduckgo for example? simple url like this from duckduckgo https://duckduckgo.com/?kt=h&kae=-1&kl=ca-en&kp=-2&kav=1&kn=1&kv=-1&kak=-1&kax=-1. This dont need any cookie and is working everytime)

**Comment by return42** [comment] 2024-04-10 13:09
Coming from https://github.com/searxng/searxng/issues/3388 .. @Gamer750, I tested all three methods .. and all three methods do work for me / I copied values from my FFox Browser to a Chromium.

At least on my instance I can say it works ... what instances do you use?

![image](https://github.com/searxng/searxng/assets/554536/162e1546-fab3-4788-8198-1df1f5e9d656)

**Comment by Gamer750** [comment] 2024-04-10 20:23
> Coming from #3388 .. @Gamer750, I tested all three methods .. and all three methods do work for me / I copied values from my FFox Browser to a Chromium.
> 
> At least on my instance I can say it works ... what instances do you use?
> 
> ![image](https://private-user-images.githubusercontent.com/554536/321247621-162e1546-fab3-4788-8198-1df1f5e9d656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3ODA4NjYsIm5iZiI6MTcxMjc4MDU2NiwicGF0aCI6Ii81NTQ1MzYvMzIxMjQ3NjIxLTE2MmUxNTQ2LWZhYjMtNDc4OC04MTk4LTFkZjFmNWU5ZDY1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQyMDIyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2I4OTFiMjhmZTYwYmFkMTkwN2QyNGM5ZGJiMTZhNmVmZjlmMjhhYjU1ZTE2Y2UxZDMyMDI5M2RhYmM3NWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JrzSqPdj6Yq_mhxdCjKSSCKCkAo9a14hMWxO4DkKPfo)

https://searxng.ca/

**Comment by return42** [comment] 2024-04-11 04:50
> https://searxng.ca/

Works also / check you browser settings.

**Closed by return42** 2024-04-11 04:50 UTC
Labels: bug

**Comment by Gamer750** [comment] 2024-04-11 12:52
> > https://searxng.ca/
> 
> Works also / check you browser settings.

When I paste the link it shows %s and not showing my settings

**Comment by return42** [comment] 2024-04-11 13:13
> When I paste the link it shows %s and not showing my settings

This is the intention of a "search URL" .. a place holder `%s` for the search term .. I guess you are looking for "to restore" .. see dialog:


![image](https://github.com/searxng/searxng/assets/554536/162e1546-fab3-4788-8198-1df1f5e9d656)
