### ISSUE TITLE
Searxng 1.0.0-1487-687bdef4 can't save preferences after updating

### ISSUE THREAD

**Issue by catfluoride** [searxng/searxng#746] opened 2022-01-13 09:07 UTC
Hi all.

After updating SearxNG to 1.0.0-1487-687bdef4, it seems impossible to save the preferences.
The preference pages opens correctly, but upon pressing "Save" the attached message appears from nginx (page unavailable).

It was working correctly before the update (sorry, can't remember which version I was using back then).

I guess it's not really a bug, but most likely some kind of misconfiguration on my part.
May someone suggest me what to check to make it work again?

SearxNG was installed using the installation script on Arch Linux, without Morty or Filtron, as this is a purely personal instance.

I can give the URL of the instance, if needed.

Thanks a lot in advance.

EDIT: nginx logs say the following

` *36 upstream sent too big header while reading response header from upstream, client: 147.xxx.xxx.xxx, server: searx.xxx.xyz, request: "POST /preferences HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/searx/socket:", host: "searx.xxx.xyz"
`

![image](https://user-images.githubusercontent.com/25054477/149298574-c3773444-ffe9-4564-875a-0e310732dcdc.png)

**Comment by dalf** [comment] 2022-01-13 09:38
It seems that the whole list of enabled and disabled engines are saved instead of the different compare to the default settings.
Perhaps related to the recent changes on /preferences

**Comment by return42** [comment] 2022-01-13 09:49
> It seems that the whole list of enabled and disabled engines

Oops now I realize, this is also the reason why we need to increase the read buffer size in filtron #738

**Comment by catfluoride** [comment] 2022-01-13 09:51
Thanks a lot for your response, @dalf . Is there any workaround I can put in place on my part? Sorry, I'd like to actively contribute to the code but my programming skills are nonexistent.

**Comment by dalf** [comment] 2022-01-13 10:21
@catfluoride : you can try to use an older version.
`1.0.0-1447-a583d095` seems a good candidate, but I haven't tested (it's a guess that this version works).

---

https://github.com/searxng/searxng/pull/708 was merged just after the commit a583d095

**Comment by catfluoride** [comment] 2022-01-13 10:24
Thank you, I need to learn how to downgrade. I'll give it a try later.

**Closed** 2022-01-13 19:28 UTC
Labels: bug

**Comment by return42** [comment] 2022-01-17 08:59
> Thank you, I need to learn how to downgrade. I'll give it a try later.

@catfluoride FYI: the issue is fixed, you do no longer need to downgrade.

**Comment by catfluoride** [comment] 2022-01-17 09:01
Yes, thank you! I noticed it and also thanked the developers on element/matrix channel :-)
