### ISSUE TITLE
Bug: google engine : no URL in the search result

### ISSUE THREAD

**Issue by ngosang** [searxng/searxng#1890] opened 2022-10-25 18:21 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.25-affd8f75

**How did you install SearXNG?**
Docker

**How To Reproduce**
Language: es-ES
Search: ramon garcia

There is a result without URL:
![image](https://user-images.githubusercontent.com/10577978/197851591-56608e65-53d3-4916-bd31-7be82a3c8170.png)

**Comment by sevmonster** [comment] 2022-10-29 09:59
Dupe of #1890, #1794

**Closed** 2022-10-29 14:47 UTC
Labels: invalid:duplicate, bug
