### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by nicfab** [searxng/searxng#2209] opened 2023-02-21 14:11 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.2.20+d669da81

**How did you install SearXNG?**
I installed SearXNG using the official wiki

**What happened?**
After running a query, the error appears.

**How To Reproduce**
See above.

**Expected behavior**
No errors.

**Screenshots & Logs**
![sshot_2023-02-21_15 10 15](https://user-images.githubusercontent.com/24752671/220368452-b8014fa5-15d9-4d4c-9f82-90efda7bdbe4.png)

**Additional context**
None

**Technical report**

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 90
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:123`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: httpx.UnsupportedProtocol
  * Percentage: 5
  * Parameters: `(None, None, 'localhost')`
  * File name: `searx/engines/startpage.py:86`
  * Function: `get_sc_code`
  * Code: `resp = get(base_url, headers=headers)`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 5
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:123`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'stopitnow.org')`
  * File name: `searx/search/processors/online.py:123`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/startpage.py:65`
  * Function: `raise_captcha`
  * Code: `raise SearxEngineCaptchaException()`

**Comment by return42** [comment] 2023-02-21 14:37
This issue is a duplicate of https://github.com/searxng/searxng/issues/1081 

FYI: I still working on this issue on my master branch .. 13f04bc47a15 .. but I haven't got the captcha problems (which are also responsible for the redirects) under control yet.

I'm going to close this issue, if you think different (not a duplicate why?) ask for reopen.

**Closed by return42** 2023-02-21 14:37 UTC
Labels: invalid:duplicate, bug

**Comment by nicfab** [comment] 2023-02-21 14:42
> This issue is a duplicate of #1081
> 
> FYI: I still working on this issue on my master branch .. [13f04bc](https://github.com/searxng/searxng/commit/13f04bc47a1503b9ccb2984d355a5b050e3fe8eb) .. but I haven't got the captcha problems (which are also responsible for the redirects) under control yet.
> 
> I'm going to close this issue, if you think different (not a duplicate why?) ask for reopen.

Thank you.
I'm sorry I haven't seen the previous issue.
