### ISSUE TITLE
Bug: rumble engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1127] opened 2022-04-21 00:19 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.18

**How did you install SearXNG?**

**What happened?** 

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 80
  * Parameters: `('404', 'Not Found', 'rumble.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 20
  * Parameters: `('200', 'OK', 'rumble.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`
  * searx/ heavy-r.com
  *

**Comment by tiekoetter** [comment] 2022-04-21 11:43
Please fill out the rest of the form.

Did you install SearXNG yourself or did you use a public instance? I can't reproduce the error with the rumble engine (https://searx.be/search?q=%21ru+test+%3Aen; https://paulgo.io/search?q=%21ru+test+%3Aen; https://searx.tiekoetter.com/search?q=%21ru+test+%3Aen)

**Comment by return42** [comment] 2022-05-08 05:59
Closed in the absence of feedback. / @ghk1991 ask to reopen issue, if you need help any more.

**Closed by return42** 2022-05-08 05:59 UTC
Labels: bug
