### ISSUE TITLE
Nothing rendering

### ISSUE THREAD

**Issue by ZackeryBayle** [searxng/searxng#1398] opened 2022-07-01 19:59 UTC
This is my first setup. I am getting nothing rendered to the page. the only error I have from the console is  `Uncaught TypeError: Cannot read properties of undefined (reading 'encrypt')`

Linux, Ubuntu LTS 20.XX
current Docker install
current searxng install

please let me know if their is any other info I can provide.

**Comment by mrpaulblack** [comment] 2022-07-01 20:28
Closing as dupe of https://github.com/searxng/searxng-docker/issues/50; Closing.

**Closed as completed by mrpaulblack** 2022-07-01 20:28 UTC
