### ISSUE TITLE
Not unescaping POST search query for display

### ISSUE THREAD

**Issue by mysteryx93** [searxng/searxng#2624] opened 2023-08-10 23:46 UTC
I'm using an instance of searx here
https://searx.garudalinux.org

Integrating into the browser search, if I integrate like this, it works, but the search terms appear with escaped characters in the search bar
```
URL:  https://searx.garudalinux.org/search
Post: q=%s
```

For example "best games 2023" shows `best%20games%202023` in the search box instead of unescaping it; but otherwise the search works fine.

If I instead configure the search like this, then everything works fine
```
https://searx.garudalinux.org/search?q=%s
```

**Comment by return42** [comment] 2023-08-11 05:43
Did you tried different instances or is the issue only on searx.garudalinux.org? .. What browser do you use? 

----

Instance from [searx.garudalinux.org](https://searx.garudalinux.org/) is not registered at https://searx.space/ .. I recommend to use a instance with monitored quality from searx.space

----

If browser supports [OpenSearch](https://github.com/searxng/searxng/issues/431) its recommended to add the instance as described in the [about page](https://searx.garudalinux.org/info/en/about)

**Comment by mysteryx93** [comment] 2023-08-11 05:49
I'm using Vivaldi browser.

I tested with `https://searx.be/` and am seeing the same behavior.

![Screenshot_15](https://github.com/searxng/searxng/assets/8528033/f686ef89-ddae-4965-9069-90f46d5d8061)

**Comment by return42** [comment] 2023-08-11 06:57
Ok, thanks for testing .. I'm not sure its caused by Vivaldi or SearXNG since SearXNG handles HTTP POST requests well without showing this issue .. I do not have Vivalidi at hand, can you test Vivaldi's POST method with other search provider like https://duckduckgo.com .. thanks!

**Comment by mysteryx93** [comment] 2023-08-11 13:15
None of the other search engines use POST; but I tried modifying DuckDuckGo integration to send via POST and the search worked...

and there was the exact same issue

So is that an issue with Vivaldi?

**Comment by return42** [comment] 2023-08-12 07:03
> So is that an issue with Vivaldi?

Yes, it is Vivaldi .. I'm going to close this issue / thanks for testing :+1:

**Closed by return42** 2023-08-12 07:03 UTC
Labels: bug
