### ISSUE TITLE
category buttons not doing anything when clicked on

### ISSUE THREAD

**Issue by rcraig12** [searxng/searxng#1625] opened 2022-08-06 15:14 UTC
**How To Reproduce**

When I use  searxng on my desktop i can change the categories on search result no problem. When I am searching using my mobile phone the category buttons do not do anything at all.

**Comment by rcraig12** [comment] 2022-08-08 11:59
How can this not be a UI bug on mobile?

**Comment by dalf** [comment] 2022-08-08 18:48
Is javascript disabled in your browser?

Currently, without javascript you have to select the category then press the search button.
This PR is going to solve this : https://github.com/searxng/searxng/pull/1414

**Comment by rcraig12** [comment] 2022-08-15 12:56
javascript is not disabled - the problem is with the android native browser and ios native browser. I note that sites using javascript on the same browser operate so this is not a disabled javascript problem.

In any case if there is a dependency on javascript should there not be a notification advising the user of this requirement on visiting the site should javascript be disabled?

**Comment by return42** [comment] 2022-08-19 13:00
> In any case if there is a dependency on javascript should there not be a notification advising the user of this requiremen

There is no dependency .. just the UX might be a little be different .. but this is what someone who disables JS knows.

Back to your issue ..

> When I am searching using my mobile phone the category buttons do not do anything at all.

We can't reproduce the issue, we tested different andriod browsers, chrome on android and on iOS and Safari and and and  .. no one can reproduce the issue.

There is only one hint left I can give: reset your SearXNG cookie if you have one ..

Sorry, there is nothing more we can do .. I close this issue.

**Closed as completed by return42** 2022-08-19 13:00 UTC

**Comment by rcraig12** [comment] 2022-08-19 16:11
Did you try the native android browser I can assure you it doesn't work as i have had many try it with the same results on different phones. also on the native ios webkit browser

**Comment by return42** [comment] 2022-08-19 16:43
Hm, IDK what a *native android browser* is .. but we tested webkit (Chrome) on iOS .. we also tested Safari on iOS .. AFAIK Safari is also based on webkit.

Did you delete your SearXNG cookie .. or what happens when you use my engine https://darmarit.org/searx/search ?

**Comment by dalf** [comment] 2022-08-19 17:04
It works with version 7.1.2 (random emulator, native browser):
![image](https://user-images.githubusercontent.com/1594191/185670642-18afd8c5-3586-4b34-97af-8f5d856cfd1c.png)

Which android version do you use?

---

[EDIT] I think https://github.com/searxng/searxng/pull/1414 would solve the issue (since there will be no JS in the loop).
