### ISSUE TITLE
Add ability for users to add private front end alternatives.

### ISSUE THREAD

**Issue by amogusussy** [searxng/searxng#1862] opened 2022-10-15 23:37 UTC
**Is your feature request related to a problem? Please describe.**

As of now, SearxNG only allows the hosts to turn on private front end redirects.

**Describe the solution you'd like**

I'd like something that allows the user to choose whether or not to replace links with their private alternatives.

Eg. 
twitter -> nitter
youtube -> invidious/piped
reddit -> libreddit/teddit
etc.

But have this togglable in the preferences, for example, if I wanted it to replace them all except reddit, I'd be able to toggle a button which does just that.

**Describe alternatives you've considered**

I've used LibRedirect, which redirects you to the private alternative front end.

There's also librex, which allows for the solution I stated above, but it's written in PHP, so isn't very fast.

**Comment by allendema** [comment] 2022-10-16 20:10
Changing domain (Frontends) can be done using the hostname_replace [plugin](https://github.com/searxng/searxng/blob/master/searx/plugins/hostname_replace.py), but you would need your own instance.

[/etc/searxng/settings.yml](https://github.com/searxng/searxng/blob/master/searx/settings.yml#L200)

```yaml
hostname_replace:
   '(.*\.)?youtube\.com$':           'invidious.namazso.eu'
   '(.*\.)?youtu\.be$':              'piped.domain.tld'
   '(.*\.)?youtube-noocookie\.com$': 'invidious.sp-codes.de'
   '(.*\.)?reddit\.com$':            'teddit.net'
   '(.*\.)?redd\.it$':               'libreddit.domain.tld'
   '(www\.)?twitter\.com$':          'nitter.unixfox.eu'
```

If you want the instances to be chosen client-side you have to look for another issue in this repository. 
https://github.com/searxng/searxng/issues/1575

**Comment by return42** [comment] 2022-10-17 06:27
Duplicate of ..

- https://github.com/searxng/searxng/issues/1575

For reference ..

- https://github.com/searxng/searxng/discussions/971
- https://github.com/searxng/searxng/discussions/970
- https://github.com/searxng/searxng/discussions/911

**Closed as completed by return42** 2022-10-17 06:27 UTC
