### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by jrcastine** [searxng/searxng#1526] opened 2022-07-19 18:38 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.19-a983db02

**How did you install SearXNG?**
searxng-docker through a portainer instance on a Raspberry Pi 4B 4GB
or manually by executing the searx/webapp.py file? -->
**What happened?**
All searches are generating this error as the first results, additional results are working as expected.

**How To Reproduce**
Perfoirm a search

**Expected behavior**
Error should not happen.

**Additional context**
This started with the last update, prior to updating the docker image, this error did not occur.-

**Technical report**

**Comment by return42** [comment] 2022-07-20 04:57
Can't reproduce this issue [!qwant foo](https://darmarit.org/searx/search?q=%21qwant%20foo&language=de-DE&time_range=None&safesearch=2&categories=none)

The technical Report is missed in your comment, I assume a "Error: httpx.ConnectTimeout" --> Duplicate of https://github.com/searxng/searxng/search?q=%22Bug%3A+qwant+engine%22&type=issues

If you see a different error please give more information and ask for reopen this issue.

**Closed by return42** 2022-07-20 04:57 UTC
Labels: invalid:duplicate, bug
