### ISSUE TITLE
Bug: gigablast engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1079] opened 2022-04-10 03:33 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.08

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 100
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/gigablast.py:96`
  * Function: `response`
  * Code: `response_json = loads(resp.text)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'gigablast.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment] 2022-04-11 19:46
Hi @jason88fr ,
Could you please fill out the bug template. @return42 It seems like gigablast changed their response, since there is a json decoder error? It is also broken in my instance and the one from unixfox...

**Comment by return42** [comment] 2022-04-12 04:38
In a `make run` instance (and on my public instance) gigablast works ..

**Comment by mrpaulblack** [comment] 2022-04-12 06:50
So its probably also a IP blocking/rate limiting thing? In that case the issue is that the blocked response is maybe not returning JSON? Do you think we can just close and ignore?

**Comment by return42** [comment] 2022-04-12 07:39
Do you have a chance to dig in the response that causes the issue? .. May be we can catch the issue and return an empty result list .. otherwise go ahead and close this issue.

**Comment by return42** [comment] 2022-05-08 06:00
Closed in the absence of feedback / ask to reopen issue, if you need help any more.

**Closed by return42** 2022-05-08 06:00 UTC
Labels: bug
