### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by Papigoe** [searxng/searxng#1870] opened 2022-10-20 01:01 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.14-1a5b0965

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 20
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by gand0rf** [comment] 2022-10-22 18:11
I am getting the same on version 2022.09.23-627dfc2a.

- searx.exceptions.SearxEngineAccessDeniedException
- Percentage: 0
- HTTP error 403
- searx/search/processors/online.py:107
- _send_http_request
- response = req(params['url'], **request_args)

**Comment by return42** [comment] 2022-10-26 05:54
duplicate of https://github.com/searxng/searxng/issues/1865

**Closed as completed by return42** 2022-10-26 05:54 UTC
Labels: invalid:duplicate
