### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by jfchevrette** [searxng/searxng#1888] opened 2022-10-25 15:03 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.21-710a3a00

**How did you install SearXNG?**

[searxng/searxng:latest](https://hub.docker.com/r/searxng/searxng)

**What happened?**

Unexpected crash error when searching

**How To Reproduce**

Enable brave, search for something

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.DecodingError
  * Percentage: 100
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-10-26 05:52
See https://github.com/searxng/searxng/issues/1815#issuecomment-1282220775

duplicate of https://github.com/searxng/searxng/search?q=httpx.DecodingError&type=issues

**Closed as completed by return42** 2022-10-26 05:52 UTC
Labels: invalid:duplicate
