### ISSUE TITLE
uwsgi.ini --> chdir error

### ISSUE THREAD

**Issue by N3S3** [searxng/searxng#1524] opened 2022-07-18 02:52 UTC
### Discussed in https://github.com/searxng/searxng/discussions/1521

<div type='discussions-op-text'>

<sup>Originally posted by **N3S3** July 17, 2022</sup>
Hi all, I used for installling docker-compose and it throws the following error for a shared instance (www.faceless.services):
...
machine: x86_64
searxng    | clock source: unix
searxng    | pcre jit disabled
searxng    | detected number of CPU cores: 1
searxng    | current working directory: /usr/local/searxng
searxng    | detected binary path: /usr/sbin/uwsgi
searxng    | chdir() to /usr/local/searx/searx-src/searx
searxng    | chdir(): No such file or directory [core/uwsgi.c line 2625]
caddy      | {"level":"info","ts":1658096138.42962,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"
...
Where [in uwsgi.ini of /usr/local/searxng?]and how do I have to define the chdir path in nano?

Thanks in advance for helping a newbie :). </div>

**Comment by mrpaulblack** [comment] 2022-07-18 21:43
Duplicate of https://github.com/searxng/searxng/discussions/1521 (lets keep the discussion there :+1: ); Closing.

**Closed as completed by mrpaulblack** 2022-07-18 21:43 UTC
Labels: invalid:duplicate
