### ISSUE TITLE
[flickr_noapi] Image results always contain stock images of Herons, regardless of the query used.

### ISSUE THREAD

**Issue by mantacid** [searxng/searxng#2586] opened 2023-08-02 03:07 UTC
**Version (as listed by one affected public instance): 2023.7.29+8b4ba20**

NOTE: This bug has occurred across several public instances, over a period of just under a year, Thus, affected versions may vary. I have included the version of the one I am currently using. Maybe one of the search engines has a broken API? Or they're doing it to punish scraping? perhaps it's SEO gone awry. whatever it is, it has made SearX barely usable for image searches.

EDIT: all the recurring images appear to be from staticflickr.

**How To Reproduce**
1. search for literally anything
2. click on images
3. scroll down

**Expected behavior**
images are for the most part related to the search query.

**Observed behavior**
Birds. Mostly Herons, but there's usually at least one image of some spoonbills.

**Screenshots & Logs**
From https://search.rhscz.eu
search term: "sonic the hedgehog"
![Screenshot 2023-08-01 195433](https://github.com/searxng/searxng/assets/123284210/c29ef97c-6f6e-4e40-a0d6-695c0ec1b5dc)

search term: "bill clinton"
![Screenshot 2023-08-01 195605](https://github.com/searxng/searxng/assets/123284210/70a969cc-f706-41ec-960b-a98381473cfc)

search term: "lenovo thinkpad x200"
![Screenshot 2023-08-01 195737](https://github.com/searxng/searxng/assets/123284210/db092a79-5aad-49be-bdeb-ef88e052806d)

**Additional context**
This issue has followed me from several public instances, despite the image engines being configured differently each time. I don't know what the birds want from me.

**Comment by mantacid** [comment] 2023-08-02 03:10
after inspecting the screenshots further, some of the nature photos appear to also be recurring.

**Comment by return42** [comment] 2023-08-02 06:34
> EDIT: all the recurring images appear to be from staticflickr.

Hi @mantacid, thanks for your serious analysis :+1: 

I can reproduce this issue by search syntax `!flickr bill clinton` / whatever search term we use, the images you marked in your screenshots are in the results of the filckr engine:

https://github.com/searxng/searxng/blob/8b4ba204b7e6469181a29c9152cc7ec880005b05/searx/settings.yml#L655-L663

--> seems engine module [`flickr_noapi`](https://github.com/searxng/searxng/blob/master/searx/engines/flickr_noapi.py) needs a review.

**Comment by obfuscated-loop** [comment] 2023-11-22 00:43
Was this fixed, or fixed itself? I cannot reproduce this at the moment.

**Comment by return42** [comment] 2023-11-22 05:29
> Was this fixed, or fixed itself? I cannot reproduce this at the moment.

Yeah, that's crazy... it fixed itself... I can no longer reproduce the problem... and my instance shows 100% reliability of flickering.

Last patch 270ad1889 was in March (long before this issue was reported).

I'm going to close this issue.

**Closed by return42** 2023-11-22 05:29 UTC
Labels: area:engine, bug

**Comment by obfuscated-loop** [comment] 2023-11-22 08:47
This has got to be the funniest bug of all time! _"Birds. Mostly Herons, but there's usually at least one image of some spoonbills."_ :rofl:
