### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by rahulkthakar** [searxng/searxng#1986] opened 2022-11-29 02:11 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.25-1314c1c5

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 0
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-11-29 07:09
duplicate of https://github.com/searxng/searxng/issues/1735#issuecomment-1234096653

**Closed as completed by return42** 2022-11-29 07:09 UTC
Labels: invalid:duplicate
