### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by dardar1129** [searxng/searxng#1634] opened 2022-08-09 04:37 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.08.08-925f3ff4

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 35
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-08-09 05:25
@dardar1129 please fill out the form .. without additional information we can't reproduce the issue (ddg does work on other SearXNG instances).  For now I close the issue, add the info we need and ask for reopen.

**Closed by return42** 2022-08-09 05:25 UTC
Labels: bug
