### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by mhaner655** [searxng/searxng#2114] opened 2023-01-19 23:14 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.01.08-4e735b28

**How did you install SearXNG? Docker-compose

Error on every search from google
**How To Reproduce**

search with google as one of the engines
**Expected behavior**

Google is included in the results
**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 0
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2023-01-20 06:39
duplicate of

- https://github.com/searxng/searxng/issues/1735#issuecomment-1234096653
- https://github.com/searxng/searxng/issues/1966

**Closed by return42** 2023-01-20 06:39 UTC
Labels: invalid:duplicate, bug
