### ISSUE TITLE
Convert JS & CSS dependencies to user preferences

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#769] opened 2022-01-17 06:00 UTC
These  [plugins](https://docs.searxng.org/dev/plugins.html) are theme dependent so they should be implemented in themes (instead of via externally injected CSS / JS)

* [x] convert `infinite_scroll.py` to user preference  #812
* [x] convert `vim_hotkeys.py` to user preference
* [x] convert `search_on_category_select.py` to user preference

**Comment by dalf** [comment] 2022-01-18 19:44
When a feature should be a embedded plugin ? By embedded plugin, I mean a plugin in this repository.
What is the purpose of a embedded plugin compare to normal code ?

Currently:
* "open in a new tab" is not a plugin (but it was implemented twice some time ago, see https://github.com/searx/searx/issues/2037 ).
* infinite scroll, vim shortcuts are plugins.

Also, why the OSM maps and the embedded video player are not displayed using plugin ?

I feel we can create a lot of small plugins. But is useful?

Some points:
* the JS & CSS is quiet small, few bytes more won't matter even if the plugin are disabled.
* at the opposite, each new plugin adds new HTTP request = it slows down the response time (even if it is better with HTTP/2, there is still an impact).
* also the plugin code are outside the theme build process:
  * the JS is not minified, not a big deal.
  * the CSS is not built using LESS. This is an issue, because the LESS mixin are not available.

About the trust in Javascript:
* if the user don't want to use javascript, it can be disabled
* if the user trusts the javascript usage at little as possible, where to draw the line? If this is a requirement, I'm more in favor of a stripe down version of searxng.min.js to the bare minimum (if the no-JS version has big issues).

So I would convert the infinite scroll and vim shortcuts plugins to normal preferences.

**Comment by not-my-profile** [comment] 2022-01-18 20:46
>each new plugin adds new HTTP request

there is nothing stopping us from bundling the plugin JS server-side with Python

>the CSS is not built using LESS. This is an issue, because the LESS mixin are not available.

I'm not familiar with LESS mixins, can you give me an example?

>if the user trusts the javascript usage at little as possible, where to draw the line?

I agree that plugins don't add much in terms of trust. IMO plugins are about extensibility. That is instances can add their own plugins.

>So I would convert the infinite scroll and vim shortcuts plugins to normal preferences.

If there's no actual reason to bundle them (server side bundling and LESS compilation could be set up), I think implementing them in a modular way could be more elegant.

I think the main selling point for implementing some of our own features as plugins is to test that our plugin system actually works (and thus can actually be used by instances to add their own plugins).

**Comment by dalf** [comment] 2022-01-18 21:53
> there is nothing stopping us from bundling the plugin JS server-side with Python



> I'm not familiar with LESS mixins, can you give me an example?

[They are like macros.](https://lesscss.org/features/#mixins-feature)

Example to manage the RTL languages:

The `rtl-left` mixin has two different definitions:
https://github.com/searxng/searxng/blob/96a1f79c6dcaa08a231ad3a28b8c17b677cddc9c/searx/static/themes/simple/src/less/style-rtl.less#L1-L3

https://github.com/searxng/searxng/blob/96a1f79c6dcaa08a231ad3a28b8c17b677cddc9c/searx/static/themes/simple/src/less/style-ltr.less#L1-L3

`detail.less` and the other .less files are compiled twice, once version with the first definition, once with the second definition. For example:

https://github.com/searxng/searxng/blob/96a1f79c6dcaa08a231ad3a28b8c17b677cddc9c/searx/static/themes/simple/src/less/detail.less#L114-L118
* when this code is compiled with the first definition, `.ltr-left(1rem);` becomes `left: 1rem`
* when this code is compiled with the second definition, `.ltr-left(1rem);` becomes `right: 1rem`

> I think implementing them in a modular way could be more elegant.

* IMO, we don't need plugin to write elegant code.
* The plugins have a cost: it requires to define an API between the "main" Javascript and the plugins (same as the `blocked_plugins ` option)

> server side bundling and LESS compilation could be set up

> I think the main selling point for implementing some of our own features as plugins is to test that our plugin system actually works (and thus can actually be used by instances to add their own plugins).

It would be a better selling point if we had some real external plugins (with the compilation steps).
A fork, some new commits, and voilà a new plugin.
The embedded plugins show half of the way.

Note perhaps OT: the external resources of the external plugins are [copied to the SearXNG repository](https://github.com/searxng/searxng/blob/96a1f79c6dcaa08a231ad3a28b8c17b677cddc9c/searx/plugins/__init__.py#L49-L110) at runtime. The idea is to use the reverse proxy (nginx, caddy, apache) to serve the static files. I'm not sure it works well all the scenarios.

---

On the timeline, I would like to first switch the default, and then deal with plugins.

**Comment by return42** [comment] 2022-01-18 22:33
Just a little bit bikeshedding from mine ...

I don't have a clear opinion but I think there is no need for "internal plugins" and for "real external plugins" the API we have (or better say not have) is not clear.  I think there is a need for "external plugins" e.g. filter functions .. but these should not manipulate CSS & JS.

When we talk about plugins I think we need to differentiate between client (HTML, CSS, JS)  and server site. ATM we have a uncontrolled mix of both, the "infinity scroll" is a good example to demonstrate, that this what we have is conceptional insufficient.

**Comment by not-my-profile** [comment] 2022-01-18 23:55
>On the timeline, I would like to first switch the default, and then deal with plugins.

If possible I'd like to address this issue beforehand because it's blocking me from fixing #713.

>ATM we have a uncontrolled mix of both

I really think that this is the smallest problem of our plugin API. A way bigger problem is that like our engine API it's misusing Python modules. We should really be using classes instead (for both plugins and engines).

>the "infinity scroll" is a good example to demonstrate

Can you elaborate?

**Comment by return42** [comment] 2022-01-19 06:07
> We should really be using classes instead (for both plugins and engines).

The old searx team had a different opinion .. they were convinced monkey patching was the best method to solve these requirements .. but now we have our own fork and old questions find new answers.

> Can you elaborate?

"infinity scroll" is not independent from the JS & CSS of the theme / this functionality needs to be implemented for each single theme.

**Comment by dalf** [comment] 2022-02-21 11:49
~Replaced by #916~ (EDIT: I misread, the issue is not closed since it is about all `vim_hotkeys` and `search_on_category_select` too)

**Comment by not-my-profile** [comment] 2022-02-21 11:53
I fail to see how that PR replaces this tracking issue. `vim_hotkeys` and `search_on_category_select` still need to be converted, no?

**Comment by return42** [comment] 2022-05-20 05:15
> These  [plugins](https://docs.searxng.org/dev/plugins.html) are theme dependent so they should be implemented in themes (instead of via externally injected CSS / JS)

The plugins do no longer import CSS nor JS .. and the vim-hotkey and the search-on-category select are now in the preferences / I close this issue.

**Comment by dalf** [comment] 2022-05-20 05:40
vim-hotkey and search-on-category are still plugins:
* https://github.com/searxng/searxng/blob/master/searx/plugins/vim_hotkeys.py
* https://github.com/searxng/searxng/blob/master/searx/plugins/search_on_category_select.py

they still need to be converted as preferences.

It would be especially useful for the search-on-category preferences because the HTML template could render either checkbox either actual button (rather than checkbox than behave like button --> it would greatly improve the UX in a text browser).

**Comment by return42** [comment] 2023-04-07 11:07
AFAI can say this issue can be closed / if not, ask for reopening.

**Comment by dalf** [comment] 2023-04-07 11:48
These two files are empty shells to provide two options:

https://github.com/searxng/searxng/blob/master/searx/plugins/vim_hotkeys.py
https://github.com/searxng/searxng/blob/master/searx/plugins/search_on_category_select.py

If the purpose is to clean up the code, the issue should remains open

**Comment by Bnyro** [comment] 2023-09-27 13:12
@return42 I think we can close this now :)

**Closed as completed** 2023-09-27 13:40 UTC
Labels: area:ui, area:plugin, javascript
