### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1958] opened 2022-11-13 18:01 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.05-d764d94a

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

this pairs along with the error I just posted moments ago.

**Comment by return42** [comment] 2022-11-14 07:14
> Version: 2022.11.05-d764d94a

update your instance .. duplicate of https://github.com/searxng/searxng/issues/1935 and solved in PR https://github.com/searxng/searxng/pull/1950

**Closed as completed by return42** 2022-11-14 07:14 UTC
Labels: invalid:duplicate
