### ISSUE TITLE
Bug: google images engine

### ISSUE THREAD

**Issue by cempack** [searxng/searxng#1494] opened 2022-07-11 13:21 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.01-5672f5ad

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 100
  * Parameters: `('200', 'OK', 'consent.google.fr')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('//script[contains(., "AF_initDataCallback({key: ")]', 'index 1 not found')`
  * File name: `searx/engines/google_images.py:107`
  * Function: `parse_urls_img_from_js`
  * Code: `img_src_script = eval_xpath_getindex(dom, '//script[contains(., "AF_initDataCallback({key: ")]', 1).text`

**Comment by mrpaulblack** [comment] 2022-07-11 20:28
Duplicate of https://github.com/searxng/searxng/issues/1432; Closing.

**Closed by mrpaulblack** 2022-07-11 20:28 UTC
Labels: invalid:duplicate, bug
