### ISSUE TITLE
Maps need to display a map, not search results.

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#3344] opened 2024-03-19 12:36 UTC
Maps need to display a map, not search results.

When the user enters  a search term  such as an address and clicks maps, a image map should be displayed instead of search results.

The user expects a map not search results.

**Comment by dalf** [comment] 2024-03-19 12:47
Duplicate of https://github.com/searxng/searxng/issues/1261

We are aware about this issue, as usual it requires time, and in addition, web dev skills.

**Closed as completed by dalf** 2024-03-19 12:47 UTC
