### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by tunisiano187** [searxng/searxng#2796] opened 2023-09-16 18:13 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.9.15+ec540a967

**How did you install SearXNG?**
Docker image 

**What happened?**
403 error

**How To Reproduce**
Search on  search.bowlman.org for example 

Some result 

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 50
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/engines/duckduckgo.py:97`
  * Function: `get_vqd`
  * Code: `res = get(query_url)`

**Comment by BernieHuang2008** [comment] 2023-09-17 00:22
Do you mean this?
![Screenshot_20230917_081458_com.microsoft.emmx.png](https://github.com/searxng/searxng/assets/88757735/c140e08d-b014-4ab0-b0e5-2c2d60f8f2f1) ![Screenshot_20230917_081811_com.microsoft.emmx.png](https://github.com/searxng/searxng/assets/88757735/6dc8a9df-3d13-4310-b8aa-b6219f561866)


Yes, with the instance you provided, there're several engines that can't use.
![Screenshot_20230917_081952_com.microsoft.emmx.png](https://github.com/searxng/searxng/assets/88757735/aabbdafd-abbb-45bb-b3d4-65169d817186)

`403` means 403-forbidden. It's probably your server's network with ddg is unstable.

Every instance has some network errors like this, so don't be so worried about it. If you're the admin of this instance, you should check your network. If not, you can report to the admin.

**Comment by bigsk1** [comment] 2023-10-03 01:16
Having same issue on docker container latest build. 

```bash 
<html><body>
<!--StartFragment-->

Exception | searx.exceptions.SearxEngineAccessDeniedException | Percentage | 100
-- | -- | -- | --
HTTP error 403
searx/search/processors/online.py:118
_send_http_request
response = req(params['url'], **request_args)

<!--EndFragment-->
</body>
</html>

LOGS

DEBUG   searx.searx.search.processor  : Suspend for 86400 seconds

ERROR   searx.engines.duckduckgo      : Searx is blocked

Traceback (most recent call last):

  File "/usr/local/searxng/searx/search/processors/online.py", line 165, in search

    search_results = self._search_basic(query, params)

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/search/processors/online.py", line 149, in _search_basic

    response = self._send_http_request(params)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/search/processors/online.py", line 118, in _send_http_request

    response = req(params['url'], **request_args)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/network/__init__.py", line 179, in post

    return request('post', url, data=data, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request

    return future.result(timeout)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result

    return self.__get_result()

           ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result

    raise self._exception

  File "/usr/local/searxng/searx/network/network.py", line 291, in request

    return await self.call_client(False, method, url, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/network/network.py", line 274, in call_client

    return Network.patch_response(response, do_raise_for_httperror)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/network/network.py", line 247, in patch_response

    raise_for_httperror(response)

  File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 75, in raise_for_httperror

    raise SearxEngineAccessDeniedException(message='HTTP error ' + str(resp.status_code))

searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400

```

**Comment by BernieHuang2008** [comment] 2023-10-03 01:33
Can I have your instance url?
@bigsk1

**Comment by BernieHuang2008** [comment] 2023-10-03 01:42
Here are some simple Quick-checks you can perform:
1. Use your browser and try to visit `ddg`.
2. If you can't visit and saw `captcha`, then you should enable searxng's bot-protection plugin and wait for some days.

**Comment by bigsk1** [comment] 2023-10-03 04:09
> Can I have your instance url? @bigsk1

is the first one oadoi.org, ok I will look into bot protection plugin

**Comment by return42** [comment] 2023-10-03 05:06
@bigsk1 can you please format your comment [above](https://github.com/searxng/searxng/issues/2796#issuecomment-1744009590) in a way its readable.

**Comment by unixfox** [comment] 2023-10-03 08:06
> > Can I have your instance url? @bigsk1
> 
> is the first one oadoi.org, ok I will look into bot protection plugin

But it's private or public instance?

**Comment by Aeris1One** [comment] 2023-10-03 11:08
Can reproduce on a private instance (no public access, login needed to access searxng).
Browsing ddg through server ip works fine with no captcha

**Comment by freeload101** [comment] 2023-10-05 21:36
** Update**:    Nail in the Coffin for me is not supporting -search ;/ I could get past everything else. I understand that this project is more about privacy. I was looking for a search engine that didn't have all the spam and SEO garbage all of them have... I switch back to Kaji that allows you to block results other people block and bring to front sites you want more at the top basicly. 

looks like !ddg is broken still but !bing seems to be working  ... here is my setup script for the config and branding I still can't remove the google stuff with sed ... but whatever ..

"NOT GOOGLE"
https://github.com/freeload101/SCRIPTS/blob/master/MISC/searxng_update.bash

**Comment by bigsk1** [comment] 2023-10-05 21:51
> > > Can I have your instance url? @bigsk1
> > 
> > 
> > is the first one oadoi.org, ok I will look into bot protection plugin
> 
> But it's private or public instance?

private is being ran in docker container and only local network 192.xx.xx.xx ,ect. must be my ip being flagged as bot activity. Not an issue just toggled it off, thanks for looking into it.

**Comment by MartinNowak** [comment] 2023-10-08 09:40
> Can reproduce on a private instance (no public access, login needed to access searxng).
> Browsing ddg through server ip works fine with no captcha

Tried to bisect this and also get a 403 response with a much older version => seems like sth. changed on ddg's side.

It simply seems that the default user-agent gets blocked by now.
https://github.com/searxng/searxng/blob/c3ab49cd903d27905d2da6f70699a55c9a74593e/searx/data/useragents.json#L10

**Comment by return42** [comment] 2023-10-08 09:55
Might related to ..?

- https://github.com/searxng/searxng/pull/2826

@jazzzooo @dalf can you reproduce the issue?

**Comment by MartinNowak** [comment] 2023-10-09 10:59
> * [[fix] update user agent #2826](https://github.com/searxng/searxng/pull/2826)

At least that PR did not fix *this* ddg issue, for now I switched to the UA of my browser (brave).

**Comment by return42** [comment] 2023-10-09 12:08
> At least that PR did not fix this ddg issue, for now I switched to the UA of my browser (brave).

@MartinNowak this PR did not fix the issue / this issue might be the cause of the issue / thats why I pinged @jazzzooo and @dalf .. :)

A soon I have time for / I will have a look.

**Comment by MartinNowak** [comment] 2023-10-09 14:18
> @MartinNowak this PR did not fix the issue / this issue might be the cause of the issue / thats why I pinged @jazzzooo and @dalf .. :)

> Tried to bisect this and also get a 403 response with a much older version => seems like sth. changed on ddg's side.

Could reproduce the issue with a version from 6 months ago.
https://github.com/searxng/searxng/issues/2796#issuecomment-1751977790

Just retried with the UA template from before #2826 and immediately get blocked by duckduckgo.

**Comment by freeload101** [comment] 2023-10-09 15:31
So I'm sure I'm not the first to think of this but feed it a mass list of known  user agents -10 years and rotate around ? Maybe have a "Troubleshooting" link that will do thingsl like : 

* make sure basic search works links --dump ( capcha check black list check etc )
* check from known proxies ( tor or even crap CoDeeN proxies I can feed you a list if you like )
* dynamic or random User Agent check
* you can use google translate to check a website or URL for a extramly fast text proxy
* Best agent tag I know of for bypassing CF and CDN DDOS https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy/blob/98b2e96dd262b032be1f18d4b74cddbdefd28cba/JAMBOREE.ps1#L922C1-L923C1 
* user check ( check the number of IP's using your server ?
* Check that number of searches each user is doing ( I guess anti botting thing alredy does this ? My server was 'private' anyway )
* submit domain in config and RDNS to virus total to see if your site is listed ( compromised etc ... )

**Comment by return42** [comment] 2023-10-10 06:38
> @MartinNowak this PR did not fix the issue / this issue might be the cause of the issue / thats why I pinged @jazzzooo and @dalf .. :)

I did some reverse engineering .. and I have to correct my first assumption; it is not the UA but the ``Referer`` header / the issue is fixed in:

- https://github.com/searxng/searxng/pull/2922

Have a look at the PR for more details.

----

In production I realized there was one more issue with the ddg-lite engine / fixed in:

- https://github.com/searxng/searxng/pull/2923

**Closed** 2023-10-10 06:40 UTC
Labels: bug

**Comment by unixfox** [comment] 2023-10-10 21:09
Duckduckgo started to straight block the IP addresses of a lot of searxng public instances.

Accessing https://duckduckgo.com from the IP address of my instance results in a "timeout".

I don't think it's related to https://github.com/searxng/searxng/commit/9197efa2a734c6934494f491f9b8dcaa89e49b62 because my instance was banned even though I didn't update it yet.

**Comment by return42** [comment] 2023-10-11 05:29
> Duckduckgo started to straight block the IP addresses of a lot of searxng public instances.

The two patches of mine from last day were not sufficient .. more work (reverse engineering) was needed. I developed another patch yesterday and then tested it on my instance first.

Here is the patch:

- https://github.com/searxng/searxng/pull/2925

**Comment by jeffalyanak-zadara** [comment] 2023-10-16 10:34
@return42's patch worked for me when applied to ` 2023.10.6+ce270961`.
