### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by danktankk** [searxng/searxng#2052] opened 2022-12-28 16:12 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.11-3a765113

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Is there a fix for this?  Been going on for a week now.  Thanks

**Comment by return42** [comment] 2022-12-28 16:26
> Version: 2022.11.11-3a765113

Please guys, you also need to do the updates and some research before you report a bug!!

Duplicate of https://github.com/searxng/searxng/issues/1854 and fixed last week in https://github.com/searxng/searxng/pull/2035

**Closed as completed by return42** 2022-12-28 16:26 UTC
Labels: invalid:duplicate

**Comment by danktankk** [comment] 2022-12-29 13:59
fair enough.  thank you.

**Comment by danktankk** [comment] 2022-12-30 08:05
updated and its still present..  so im not sure how much research I need to do at this point.........................

**Comment by return42** [comment] 2022-12-30 08:14
To many points on your keyboard? .. use your energy to fill out the bug report above and we can reopen this issue.

Is you instance public?

**Comment by danktankk** [comment] 2023-01-03 04:34
No, it isnt public...  Honestly..  you seem a bit too taxed to deal with maintaining this repo.  I'll just nix using this.  thanks for the moment it worked.
