### ISSUE TITLE
Usage of piped \ invidious embedded video player

### ISSUE THREAD

**Issue by TalOrenshtein** [searxng/searxng#3049] opened 2023-12-05 08:42 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I recently found out that piped has an embedded player that can be used instead an embedded youtube player when you search for videos, and I thought it'll be useful for users to have an option to toggle between them.

**Describe alternatives you've considered**
You can use invidious's version of the embedded player instead.

**Additional context**
- You might want to check out [LibRedirect](https://codeberg.org/LibRedirect/)'s redirection of embedded youtube videos (and lots of other stuff that might be useful too) as an example.
- The front-ends' instances will probably be chosen by the admin.
- I tend to gravitate towards piped's embedded player because Invidious don't always proxy the video and I didn't check if, for example, it proxies by default when using the embedded player, and the whole point is that the user don't access youtube directly. So it might be inconsistent and depended on the chosen instance's default settings. It's also worth noting that it's also the case for SearXNG's behavior right now when using the embedded player (accessing youtube directly).

**Comment by Bnyro** [comment] 2023-12-14 19:23
You can already search videos via `!piped foo` in order to receive Piped results with Piped embeds.

Hence there's no need to modify the existing YouTube search engine.

If you're referring to normal search results, it's a duplicate of https://github.com/searxng/searxng/issues/1575.

**Comment by return42** [comment] 2024-02-20 19:31
You can also redirect youtube URLs to piped:

- https://github.com/searxng/searxng/discussions/970#discussioncomment-7131767

**Closed as completed by return42** 2024-02-20 19:31 UTC
