### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by betsaleel777** [searxng/searxng#1293] opened 2022-06-07 09:38 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.04-0ce9d9e8

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-06-07 10:34
Please fill out the rest of the form.

About your issue `Too many request` from google engine --> https://github.com/searxng/searxng/issues/1146#issuecomment-1111765874

duplicate of: https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22

**Closed by return42** 2022-06-07 10:34 UTC
Labels: invalid:duplicate, bug
