### ISSUE TITLE
I would like the search to begin immediately after selecting a search string from the autocomplete list.

### ISSUE THREAD

**Issue by chattytak** [searxng/searxng#1018] opened 2022-03-26 14:20 UTC
**Is your feature request related to a problem? Please describe.**

Currently, selecting a search string from an autocomplete candidate will cancel the text input mode.
Therefore, if the user relies on autocomplete, he/she cannot continue to enter the search string. (It will be interrupted.)
However, there is a pause simply because the search does not start in that state.
I would think that if the user relied on autocomplete, the search would start immediately with that string, and if they wanted to edit the string further afterwards, they could do so from the screen after the search.
What do you think?

**Describe the solution you'd like**

The search should begin immediately when the user selects a string from the autocomplete candidates.

**Describe alternatives you've considered**

**Additional context**

**Comment by mrpaulblack** [comment] 2022-03-26 15:30
Agreed; I wanted to do this in https://github.com/searxng/searxng/pull/963, but just dont know how tbh. We use a rather old autocomplete JS lib and we would need to do a patch to make this work I guess...

**Comment by return42** [comment] 2022-03-26 16:08
I think this is a duplicate of https://github.com/searxng/searxng/issues/778#issuecomment-1016593816. Is it OK to close this issue in favorite of #778?

**Closed as completed** 2022-03-26 16:12 UTC
Labels: area:ui
