### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by Papigoe** [searxng/searxng#1871] opened 2022-10-20 01:02 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.14-1a5b0965

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 55
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by Mau-Bomani** [comment] 2022-10-22 23:00
![Screenshot_20221022_165704](https://user-images.githubusercontent.com/116457487/197365410-1a75f17f-a002-4fe6-99f2-5750a62d0575.jpg)

Turn it off them back on. That solved this issue for me

**Comment by atuleu** [comment] 2022-10-24 08:46
Have the same issue, but turn off/ restart doesn't work for me

Issues happened after turning completion on for google. Maybe related ?

**Comment by return42** [comment] 2022-10-26 05:48
did you tried `use_mobile_ui` ... https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google

```yaml
- name: google
  ...
  use_mobile_ui: true
```

Duplicate of https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+use_mobile_ui

**Closed by return42** 2022-10-26 05:48 UTC
Labels: bug

**Comment by atuleu** [comment] 2022-10-26 07:56
@return42 Should not then just be enabled by default ?
