### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by learn2reid** [searxng/searxng#1952] opened 2022-11-11 21:01 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.07

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 0
  * Parameters: `('500', 'Internal Server Error', 'www.google.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-11-12 06:16
> Version: 2022.11.07

update your instance .. duplicate of https://github.com/searxng/searxng/issues/1935 and solved in PR https://github.com/searxng/searxng/pull/1950

**Closed by return42** 2022-11-12 06:16 UTC
Labels: bug
