### ISSUE TITLE
Bug: DuckDuckGo disallows access

### ISSUE THREAD

**Issue by RaptaG** [searxng/searxng#2037] opened 2022-12-22 18:55 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.16-b9274821

**What happened?**

DuckDuckGo returns a 403 error (access denied).

**How To Reproduce**

1. Enable the `duckduckgo` search engine
2. Search something
3. Look on the top right and you'll see the error

**Expected behavior**

DuckDuckGo allowing access.

**Screenshots & Logs**

![Bug](https://user-images.githubusercontent.com/77157639/209206474-560057c8-7dc4-48d2-9647-c10377aeb147.png)

**Additional context**

Instance used: https://search.rhscz.eu

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by schopenhauer** [comment] 2022-12-22 19:38
Same issue my Docker instance of searxng

**Comment by Error00101** [comment] 2022-12-22 21:16
Had the same issue today with my docker instance.
But today was patchday for me: Pulling the Docker container again fixed the bug for me.

**Comment by LalleSX** [comment] 2022-12-22 23:02
Same issue, **not** on Docker

**Comment by return42** [comment] 2022-12-23 06:07
> Version: 2022.12.16-b9274821

Please guys, you also need to do the updates and some research before you report a bug.

Duplicate of https://github.com/searxng/searxng/issues/1854 and fixed yesterday in https://github.com/searxng/searxng/pull/2035

**Closed by return42** 2022-12-23 06:07 UTC
Labels: invalid:duplicate, bug
