### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by jason-eu** [searxng/searxng#1081] opened 2022-04-10 03:34 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.08

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 70
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 30
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/startpage.py:66`
  * Function: `raise_captcha`
  * Code: `raise SearxEngineCaptchaException(suspended_time=7 * 24 * 3600)`

**Comment by mrpaulblack** [comment] 2022-04-11 19:53
@return42 @tiekoetter startpage is returning CAPTCHA for a while now... Idk if this is fixable, maybe its a lost cause... :/

**Comment by dalf** [comment] 2022-04-11 20:11
startpage still works on my instance, do we have an idea how much requests are needed to trigger the CAPTCHA?

**Comment by return42** [comment] 2022-04-14 13:57
> startpage still works on my instance

same on my instance .. tbh startpage is disabled by default in my instance .. that might be the reason why  my instance does not get a CAPTCHA from startpage ..

> do we have an idea how much requests are needed to trigger the CAPTCHA?

I don't know .. I tried to trigger but before I reached the limit on Startpage, my filtron blocks my client ;-)

Oops .. after testing a while the same request .. again and again .. now I get redirects:

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 85
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 15
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

I can reproduce this on my local `make run` instance .. I will dig ..

---

Here is the log

```
DEBUG   searx.network.startpage       : HTTP Request: GET https://startpage.com/sp/search?query=foo&page=1&cat=web&sc=h78RPDkQIWIf20&language=deutsch&lui=deutsch "HTTP/1.1 307 Temporary Redirect" (text/html)
DEBUG   searx.network.startpage       : HTTP Request: GET https://www.startpage.com/sp/search?query=foo&page=1&cat=web&sc=h78RPDkQIWIf20&language=deutsch&lui=deutsch "HTTP/1.1 307 TEMPORARY REDIRECT" (text/html; charset=utf-8)
DEBUG   searx.network.startpage       : HTTP Request: GET https://www.startpage.com/sp/captcha#?bc=DE&bi=EWE-Tel+GmbH&be=3d6da692a57359b57dd3c3df78a969a2&bds_t=1649944595T186368187419a3153347bb6f08acd2d4147ee64cf67fc573615b58843749c277&cat=web&language=deutsch&sc=h78RPDkQIWIf20&lui=deutsch&query=foo&t=&cmd=gen_page "HTTP/1.1 200 OK" (text/html; charset=utf-8)
WARNING searx.engines.startpage       : ErrorContext('searx/search/processors/online.py', 105, 'count_error(', None, '2 redirects, maximum: 0', ('200', 'OK', 'www.startpage.com')) True
```

After 10 times repeating the same query startpage does redirect me .. very interesting: `?bc=DE&bi=EWE-Tel+GmbH&` is in the redirect URL .. this is the name of my internet provider. And behind the URL of the redirect there is a CAPTCHA dialogue.

To sum:

1. we have about 10 startpage request before a CAPTCHA dialogue is triggered
2. redirects are redirects to CAPTCHA
3. I don't know a solution to prevent this CAPTCHA

---

Update: in the starpage engine we have a HTTP request to _"Get an actual `sc` argument from startpage's home page"_ .. to me it seems this request is redirected and this request raises a `SearxEngineCaptchaException` we see in the initial https://github.com/searxng/searxng/issues/1081#issue-1198858264

To be clear .. we have the _redirect errors_ caused by the search request and we have the _CAPTCHA errors_ caused by the request that tries to get a `ac` argument .. the latter one was added in 21e884f369

https://github.com/searxng/searxng/blob/09230bfad9dea35a6ed112ea7096935d1c821bd9/searx/engines/startpage.py#L69-L104


```
  File "SearXNG/searx/engines/startpage.py", line 126, in request
    'sc': get_sc_code(params['headers']),
  File "SearXNG/searx/engines/startpage.py", line 89, in get_sc_code   <---- !!!
    raise_captcha(resp)
  File "SearXNG/searx/engines/startpage.py", line 67, in raise_captcha
    raise SearxEngineCaptchaException(suspended_time=7 * 24 * 3600)
```

**Comment by return42** [comment] 2023-03-29 08:32
Startpage CAPTCHA is hard to avoid .. PR:

- https://github.com/searxng/searxng/pull/2269

brings a new code base for startpage (e9afc4f8ce2d).

My subjective feeling is that the situation has improved somewhat, but there are still CAPTCHAs

I am going to close this issue ..

If we have problems with startpage again, we should open a new issue, because the code base has changed a lot in the meantime and can't be compared to what we had when this issue was opened.

**Closed by return42** 2023-03-29 08:32 UTC
Labels: area:i18n, CAPTCHA, bug
