### ISSUE TITLE
Bing news results return invalid images

### ISSUE THREAD

**Issue by ItzCrazyKns** [searxng/searxng#3502] opened 2024-05-22 03:10 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
The version is `2024.5.17+ec41b5358`

**How did you install SearXNG?**
SearXNG Docker

**What happened?**
When we use bing news search engine to perform a search the images returned are as follows:
`https://www.bing.com/https://www.bing.com/th?id=OVFT.59wS32ymUw02ORj5FG-Qai&pid=News&w=234&h=132&c=14&rs=2&qlt=30`

As you can see it has the `www.bing.com` twice and is caused by a piece of code in the Bing news search engine file that adds it to the image URLs.

**How To Reproduce**
1. Open SearXNG
2. Use Bing news search engine and search something
3. Check the URL of any image (none of the images work)

**Expected behavior**
It should return the correct image URL, i.e `https://www.bing.com/th?id=OVFT.59wS32ymUw02ORj5FG-Qai&pid=News&w=234&h=132&c=14&rs=2&qlt=30`

**Comment by Bnyro** [comment] 2024-06-14 12:44
Can't reproduce, all images load perfectly fine for me. (I'm located in Europe).

**Comment by return42** [comment] 2024-06-20 10:35
We can't reproduce the issue / at least from Europe we don't have issues .. I close this issue .. if someone has this issue, please give us some more info and ask to reopen.

**Comment by ItzCrazyKns** [comment] 2024-06-25 05:26
Hi @return42, the issue happens when you don't pass a search query. For example:

Without search query:
![image](https://github.com/searxng/searxng/assets/95534749/be46d61f-72ba-477a-85eb-96392bb8f413)

With search query:
![image](https://github.com/searxng/searxng/assets/95534749/e7d40387-46bb-4ba9-a009-270aef90eaab)

**Comment by return42** [comment] 2024-06-25 06:26
> Hi @return42, the issue happens when you don't pass a search query.

Thanks :+1: .. fixed in #3606

**Closed** 2024-06-25 09:12 UTC
Labels: cannot reproduce, bing-engine, bug
