### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by ppfeufer** [searxng/searxng#2440] opened 2023-05-17 12:45 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.5.13+1fc268a5

**How did you install SearXNG?**

searxng-docker

**What happened?**

Regular search

**How To Reproduce**

Search something

**Expected behavior**

No error message

**Screenshots & Logs**

![image](https://github.com/searxng/searxng/assets/2989985/fb06c7d4-9eeb-4f5c-ba0c-a798c0a54cd2)

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 5
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:129`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

**Comment by return42** [comment] 2023-05-17 12:53
Seems qwant begins to fail / I have the same issue ..

----

A `make run` instance on my desktop didn't have this issue .. lets wait and see ..

**Comment by return42** [comment] 2023-05-17 12:58
Sorry, to late I see we already trace this issue in https://github.com/searxng/searxng/issues/2011 .. I close this one as duplicate of ..

**Closed by return42** 2023-05-17 12:58 UTC
Labels: invalid:duplicate, bug
