### ISSUE TITLE
Errors produced on server when doing a search on the webpage.

### ISSUE THREAD

**Issue by gand0rf** [searxng/searxng#1913] opened 2022-10-29 20:20 UTC
Hello. I recently updated my linode server hosting searxng, and had some issues with getting it back up. 
I was able to and decided while I was still connected to test the page on my phone. As I searched and 
switched tabs to images, I got the following output from my server terminal.

> 2022-10-29 20:08:50,211 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
> searxng    | cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
> searxng    | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f9caa25fb50 pid: 9 (default app)
> searxng    | 2022-10-29 20:09:32,218 WARNING:searx.engines.startpage: ErrorContext('searx/engines/startpage.py', 96, 'raise SearxEngineResponseException(', 'TypeError', None, ('SearxEngineResponseException() takes no keyword arguments',)) False
> searxng    | 2022-10-29 20:09:32,219 ERROR:searx.engines.startpage: exception : SearxEngineResponseException() takes no keyword arguments
> searxng    | Traceback (most recent call last):
> searxng    |   File "/usr/local/searxng/searx/engines/startpage.py", line 93, in get_sc_code
> searxng    |     href = eval_xpath(dom, '//a[@class="footer-home__logo"]')[0].get('href')
> searxng    | IndexError: list index out of range
> searxng    | 
> searxng    | During handling of the above exception, another exception occurred:
> searxng    | 
> searxng    | Traceback (most recent call last):
> searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 154, in search
> searxng    |     search_results = self._search_basic(query, params)
> searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 128, in _search_basic
> searxng    |     self.engine.request(query, params)
> searxng    |   File "/usr/local/searxng/searx/engines/startpage.py", line 124, in request
> searxng    |     'sc': get_sc_code(params['headers']),
> searxng    |   File "/usr/local/searxng/searx/engines/startpage.py", line 96, in get_sc_code
> searxng    |     raise SearxEngineResponseException(
> searxng    | TypeError: SearxEngineResponseException() takes no keyword arguments
> searxng    | 2022-10-29 20:10:14,132 WARNING:searx.engines.startpage: ErrorContext('searx/engines/startpage.py', 96, 'raise SearxEngineResponseException(', 'TypeError', None, ('SearxEngineResponseException() takes no keyword arguments',)) False
> searxng    | 2022-10-29 20:10:14,138 ERROR:searx.engines.startpage: exception : SearxEngineResponseException() takes no keyword arguments
> searxng    | Traceback (most recent call last):
> searxng    |   File "/usr/local/searxng/searx/engines/startpage.py", line 93, in get_sc_code
> searxng    |     href = eval_xpath(dom, '//a[@class="footer-home__logo"]')[0].get('href')
> searxng    | IndexError: list index out of range
> searxng    | 
> searxng    | During handling of the above exception, another exception occurred:
> searxng    | 
> searxng    | Traceback (most recent call last):
> searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 154, in search
> searxng    |     search_results = self._search_basic(query, params)
> searxng    |   File "/usr/local/searxng/searx/search/processors/online.py", line 128, in _search_basic
> searxng    |     self.engine.request(query, params)
> searxng    |   File "/usr/local/searxng/searx/engines/startpage.py", line 124, in request
> searxng    |     'sc': get_sc_code(params['headers']),
> searxng    |   File "/usr/local/searxng/searx/engines/startpage.py", line 96, in get_sc_code
> searxng    |     raise SearxEngineResponseException(
> searxng    | TypeError: SearxEngineResponseException() takes no keyword arguments

The site works just fine. All i am getting on it right now is the "Error! Engine cannot retrieve results: startpage (unexpected crash)".
Other than that, the website is working fine. Thought I would drop this hear just in case no one else had seen the messages yet.

**Comment by return42** [comment] 2022-10-30 07:38
Thanks for your detailed bug report :+1:  ... I add this https://github.com/searxng/searxng/issues/1884#issuecomment-1296150615 and close this issue, as duplicate of https://github.com/searxng/searxng/issues/1884.

**Closed by return42** 2022-10-30 07:38 UTC
Labels: invalid:duplicate, bug
