### ISSUE TITLE
Alignment: wide

### ISSUE THREAD

**Issue by privacyguy123** [searxng/searxng#2677] opened 2023-08-24 20:04 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem - but left/center align both don't look right to me ... if results were "wider" and filled more of the screen it would be more pleasing to the eye.

**Describe the solution you'd like**
Some way to make results "wider"

**Describe alternatives you've considered**
Userstyle from 2017 that didn't work

**Comment by unixfox** [comment] 2023-08-24 20:09
probably duplicate of https://github.com/searxng/searxng/issues/1169

**Comment by privacyguy123** [comment] 2023-08-25 09:30
make this make sense to me - Im currently messing about in Stylus using that Github Wide code as a guide and I can get everything else to move and change shape except the width of the search results and info box :S

**Comment by dalf** [comment] 2023-08-25 14:34
> Im currently messing about in Stylus using that Github Wide code

Can you share your code? This may help to start the work on that subject.

**Comment by return42** [comment] 2023-09-06 14:44
I close this issue in lack of feedback .. BTW its more or less duplicate of https://github.com/searxng/searxng/issues/1169

**Closed as completed by return42** 2023-09-06 14:44 UTC
