### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by Remember2fart** [searxng/searxng#1106] opened 2022-04-16 18:59 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.11

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 75
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 25
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/startpage.py:66`
  * Function: `raise_captcha`
  * Code: `raise SearxEngineCaptchaException(suspended_time=7 * 24 * 3600)`

**Comment by tiekoetter** [comment] 2022-04-16 19:02
Did you use a public instance or install SearXNG yourself?

Without filling out the rest of the form we can't really help you.

Is this related to #1103?

**Comment by return42** [comment] 2022-04-17 07:01
FYI: I am just working on a fix / it is a duplicate of https://github.com/searxng/searxng/issues/1081

**Closed by return42** 2022-04-17 07:01 UTC
Labels: bug
