### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by stella-kitten** [searxng/searxng#2036] opened 2022-12-22 15:27 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.16-b9274821

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2022-12-22 15:32
> Version: 2022.12.16-b9274821

update SearXNG / duplicate of https://github.com/searxng/searxng/issues/1854 and fixed 1 hour ago in https://github.com/searxng/searxng/pull/2035

**Closed as completed by return42** 2022-12-22 15:32 UTC
Labels: invalid:duplicate
