### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by prem2277** [searxng/searxng#2500] opened 2023-06-15 11:32 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.6.12

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment] 2023-06-15 11:45
@prem2277 please fill out the form .. at least give us the URL of the instance you used.

> Percentage: 0

Take into account this might be a temporary issue as its percentage is by zero (below 1%).

duplicate of https://github.com/searxng/searxng/issues/2498 ?

I reopen the issue as soon we get a feedback from yours / thanks :+1:

**Closed by return42** 2023-06-15 11:45 UTC
Labels: bug
