### ISSUE TITLE
Bug: text overlap

### ISSUE THREAD

**Issue by BernieHuang2008** [searxng/searxng#1304] opened 2022-06-10 09:46 UTC
![Screenshot_20220610.png](https://user-images.githubusercontent.com/88757735/173038106-4e0c1d81-315b-4a29-81f0-722ed1fd5c2a.png)
I just found some results like this.

PS: I'm using the highest version, and I found it in almost all the version.

**Comment by mrpaulblack** [comment] 2022-06-10 09:49
Hi @BernieHuang2008 ,
can you please share your device and screen resolution? IF your browser does not use your full screen resolution, how big is your browser window?

**Comment by BernieHuang2008** [comment] 2022-06-10 09:56
Hi , thanks for your reply to this issue.
My screen resolution is 2560x1600 , and I'm using my Android pad (Android 10).
and I'm using Microsoft Edge that time .
Hope these will help you.
:)

**Comment by BernieHuang2008** [comment] 2022-06-10 23:18
Hi~
If I found the right file, then I think I solved this bug.
Please look for [PR#1312](https://github.com/searxng/searxng/pull/1312).

**Comment by return42** [comment] 2023-09-06 07:54
@BernieHuang2008 does the issue persist?

**Comment by BernieHuang2008** [comment] 2023-09-06 10:02
@return42 

Sorry, but it seems that the bug is still exist ...

![Screenshot_20230906_175940_com.microsoft.emmx.png](https://github.com/searxng/searxng/assets/88757735/49febbe2-1451-40dd-b213-c7c5ef7afc5c)

I'm still interested in this problem, so if you need my help, ask any time please.

**Comment by dalf** [comment] 2023-09-06 10:10
Which browser do you use?

**Comment by BernieHuang2008** [comment] 2023-09-06 10:23
Still MS Edge, version 116.0.1938.58, on Android phone.

**Comment by return42** [comment] 2023-09-06 12:26
Both are flex containers 

![image](https://github.com/searxng/searxng/assets/554536/effeada2-7444-43db-99d2-4c77a1383b5a)

![image](https://github.com/searxng/searxng/assets/554536/1be9a542-1fe4-41d5-b3cb-24e3cdcfe9cf)

CSS Flexible Box Layout Module is Fully Supported on Microsoft Edge, seems Edge for mobile has issues with / I can't find Edge for mobile on any compatibility list .. not sure what we can do.

@dalf do you have a clue? .. otherwise I will close this issue as related to Edge for mobile.

**Comment by BernieHuang2008** [comment] 2023-09-06 12:52
I think you can close it. If I found any valuable clues, I will open a new issue.

Thank you for all your help!

**Comment by dalf** [comment] 2023-09-06 13:05
I can't reproduce the bug on Edge Mobile 116.0.1938.64 (Android 13).
My phone seems a little wider than on the screenshot :  perhaps there is a CSS media query that breaks the display on smaller screen.

**Comment by BernieHuang2008** [comment] 2023-09-06 13:23
And I've tried on another browser on my phone, it's completely normal. So it's probably a problem of my phone+Edge.

**Comment by return42** [comment] 2023-09-06 13:29
@BernieHuang2008 thanks for your cooperation .. I close this issue / if you think it should be open for some reason, ask to reopen.

**Closed by return42** 2023-09-06 13:29 UTC
Labels: area:ui, bug
