### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by Aky9821** [searxng/searxng#1865] opened 2022-10-19 06:21 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.10.17

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:122`
  * Function: `response`
  * Code: `get(url_ping, headers=headers_ping)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: lxml.etree.ParserError
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/engines/duckduckgo.py:128`
  * Function: `response`
  * Code: `doc = fromstring(resp.text)`

**Comment by return42** [comment] 2022-10-27 15:54
duplicate of https://github.com/searxng/searxng/issues/1854 & https://github.com/searxng/searxng/issues/1812

**Closed as completed** 2022-10-27 15:53 UTC
Labels: invalid:duplicate
